import Head from "next/head";
import ShowLayout from "../components/layouts/ShowLayout";
import Header1 from "../components/Header/Header";
import Header2 from "../components/Header2/Header";
import Header3 from "../components/Header3/Header3";
import Header4 from "../components/Header4/Header";

export default function Home() {
  return (
    <ShowLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>All Header</h1>
      <div className="comp-space">
        <Header1 />
      </div>
      <div className="comp-space">
        <Header2 />
      </div>sd
      <div className="comp-space">
        <Header3 />
      </div>
      <div className="comp-space">
        <Header4 />
      </div>
    </ShowLayout>
  );
}
